package com.ufcstudy.domain.strategy;

public enum OpportunityRejectionCode {
    MAPPING_NOT_APPROVED,
    SETTLEMENT_NOT_EXACT,
    SPORTSBOOK_SNAPSHOT_MISSING,
    OPPOSING_SPORTSBOOK_SNAPSHOT_MISSING,
    PREDICTION_SNAPSHOT_MISSING,
    SPORTSBOOK_SNAPSHOT_IN_FUTURE,
    PREDICTION_SNAPSHOT_IN_FUTURE,
    SPORTSBOOK_SNAPSHOT_STALE,
    PREDICTION_SNAPSHOT_STALE,
    SOURCE_TIME_GAP_EXCEEDED,
    INSIDE_PREFIGHT_CUTOFF,
    EVENT_ALREADY_STARTED,
    MARKET_SPREAD_TOO_WIDE,
    INVALID_SPORTSBOOK_ODDS,
    INVALID_PREDICTION_PROBABILITY,
    INSUFFICIENT_SPORTSBOOK_OUTCOMES,
    EV_BELOW_THRESHOLD,
    DUPLICATE_OFFICIAL_OPPORTUNITY,
    DATA_INCONSISTENCY
}